(function(){
  'use strict';
  const $=id=>document.getElementById(id), SAVE_KEY='naiwa-pegs.progress.v1';
  const ui={board:$('board'),mascot:$('mascot'),fire:$('fire'),aim:$('aim'),angle:$('angle'),pause:$('pause'),retry:$('retry'),menu:$('menu'),num:$('level-num'),remaining:$('remaining'),balls:$('balls'),title:$('level-title'),hint:$('hint'),combo:$('combo-label'),mood:$('mood'),toast:$('toast')};
  let saved={unlocked:0,completed:[],best:[]};
  try{const x=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(x&&typeof x==='object'){saved.unlocked=Math.max(0,Math.min(5,Number.isInteger(x.unlocked)?x.unlocked:0));saved.completed=Array.isArray(x.completed)?x.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<6):[];saved.best=Array.isArray(x.best)?x.best.slice(0,6):[];}}catch(_){/* Private mode or corrupt saves must not stop the game. */}
  let state=PegSim.create(saved.unlocked),angle=0,paused=false,ready=false,renderer,dragId=null,keys=new Set(),lastTime=0,accum=0,toastTime=0,roundSaved=false,menuMode='',roundDelay=0;
  let practiceSeconds=0,playedShots=0;
  const image=new Image();image.src='assets/naiwa-expressions.png';
  function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(saved))}catch(_){}}
  function setAim(value){angle=Math.max(-68,Math.min(68,Number(value)||0));ui.aim.value=angle;ui.angle.value=Math.round(angle)+'°';}
  function say(text,seconds=1.6){ui.toast.textContent=text;toastTime=seconds;ui.toast.classList.add('on')}
  function refresh(){ui.num.textContent=String(state.levelIndex+1).padStart(2,'0');ui.remaining.textContent=PegSim.remaining(state);ui.balls.textContent=state.ballsLeft;ui.title.textContent=PegLevels[state.levelIndex].title;ui.combo.textContent=state.combo>=2?state.combo+' 连击':'';ui.fire.disabled=!ready||paused||state.phase!=='ready';ui.fire.innerHTML=state.phase==='flying'?'弹跳中 <span>●</span>':'发射 <span>↗</span>';ui.aim.disabled=paused||state.phase!=='ready';ui.mood.textContent=state.phase==='lost'?'差一点，再来！':state.phase==='won'?'笑醒啦！':state.combo>=3?'哈哈哈哈！':state.phase==='flying'?'会弹去哪呢？':'等你这一发';}
  function startLevel(i){state=PegSim.create(i);setAim(0);paused=false;roundSaved=false;roundDelay=0;accum=0;keys.clear();dragId=null;toastTime=0;ui.toast.classList.remove('on');if(renderer)renderer.reset();closeMenu();ui.hint.textContent=i<2?'拖动瞄准 · 松开发射 · 入桶返还一球':'同标记笑醒一组 → 软垫翻转 3 秒';refresh();}
  function fire(){if(!ready||paused)return;if(PegSim.launch(state,angle)){playedShots++;toastTime=0;ui.toast.classList.remove('on');refresh()}}
  function closeMenu(){if(ui.menu.open)ui.menu.close();paused=false;menuMode='';keys.clear();accum=0;lastTime=performance.now();refresh();if(ready)ui.board.focus({preventScroll:true})}
  function action(label,handler){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=handler;$('dialog-actions').append(b)}
  function showMenu(mode){if(!ready)return;menuMode=mode;paused=true;keys.clear();dragId=null;$('dialog-actions').replaceChildren();$('level-picker').replaceChildren();$('about-copy').hidden=mode!=='about';
    if(mode==='win'){const final=state.levelIndex===5;$('dialog-tag').textContent=final?'六盘全部笑醒':'这一盘，笑醒了';$('dialog-title').textContent=final?'今天的快乐收工！':'下一盘，继续营业';$('dialog-copy').textContent='用了 '+state.shots+' 颗弹珠 · 最高 '+state.bestCombo+' 连击'+(state.catches?' · 接回 '+state.catches+' 球':'')+(final?'。试试用更少的弹珠再来一轮。':'。');action(final?'再玩一轮':'下一关 →',()=>startLevel(final?0:state.levelIndex+1));action('重玩本关',()=>startLevel(state.levelIndex));}
    else if(mode==='lose'){$('dialog-tag').textContent='弹珠暂时用完了';$('dialog-title').textContent='还差 '+PegSim.remaining(state)+' 只就笑醒';$('dialog-copy').textContent='盘面保持一样。试着从另一侧切入，或等回收桶走过来。';action('同盘再来 ↻',()=>startLevel(state.levelIndex));}
    else {$('dialog-tag').textContent=mode==='about'?'怎么玩':'休息一下';$('dialog-title').textContent=mode==='about'?'瞄准，然后看它弹。':'弹珠先停在这里';$('dialog-copy').textContent=mode==='about'?'六盘小挑战，瞄准第一跳，发现后面的连锁。':PegLevels[state.levelIndex].tip;action('继续玩',closeMenu);action('重来本关',()=>startLevel(state.levelIndex));}
    if(mode!=='about'){PegLevels.forEach((l,i)=>{const b=document.createElement('button');b.textContent=saved.completed.includes(i)?'✓ '+(i+1):String(i+1);b.disabled=i>saved.unlocked;b.className=i===state.levelIndex?'current':'';b.setAttribute('aria-label','第'+(i+1)+'关 '+l.title+(i>saved.unlocked?'，尚未解锁':''));b.onclick=()=>startLevel(i);$('level-picker').append(b)})}
    if(!ui.menu.open)ui.menu.showModal();refresh();}
  function processEvents(){for(const e of state.events.splice(0)){renderer.event(e);if(e.type==='group'&&state.pads.length)say('笑醒一组！软垫转向 ↔',1.5);if(e.type==='catch')say('接住了！弹珠 +1',1.4);if(e.type==='shotEnd'){if(e.reason==='stuck'||e.reason==='timeout')say('卡球已清走，继续下一发',1.4);else if(state.phase==='ready'&&e.combo>=3)say(e.combo+' 连击！再来一发',1.2)}if(e.type==='win'){if(!roundSaved){saved.unlocked=Math.max(saved.unlocked,Math.min(5,state.levelIndex+1));if(!saved.completed.includes(state.levelIndex))saved.completed.push(state.levelIndex);saved.best[state.levelIndex]=Math.min(saved.best[state.levelIndex]||999,state.shots);save();roundSaved=true;}say('全员笑醒！',.65);roundDelay=.7;}if(e.type==='lose')roundDelay=.3;}}
  function aimAt(event){const r=ui.board.getBoundingClientRect(),x=(event.clientX-r.left)*480/r.width,y=(event.clientY-r.top)*620/r.height;setAim(Math.atan2(x-240,Math.max(30,y-62))*180/Math.PI);}
  ui.board.addEventListener('pointerdown',e=>{if(paused||!ready||state.phase!=='ready'||(e.pointerType==='mouse'&&e.button!==0))return;dragId=e.pointerId;ui.board.setPointerCapture(e.pointerId);ui.board.focus({preventScroll:true});aimAt(e);e.preventDefault()});
  ui.board.addEventListener('pointermove',e=>{if(paused||state.phase!=='ready')return;if(dragId===e.pointerId||(e.pointerType==='mouse'&&dragId===null))aimAt(e)});
  ui.board.addEventListener('pointerup',e=>{if(dragId!==e.pointerId)return;aimAt(e);dragId=null;if(ui.board.hasPointerCapture(e.pointerId))ui.board.releasePointerCapture(e.pointerId);fire();e.preventDefault()});
  ui.board.addEventListener('pointercancel',()=>{dragId=null});ui.board.addEventListener('lostpointercapture',()=>{dragId=null});
  ui.aim.addEventListener('input',e=>setAim(e.target.value));ui.fire.onclick=fire;ui.retry.onclick=()=>startLevel(state.levelIndex);ui.pause.onclick=()=>showMenu('pause');$('about').onclick=()=>showMenu('about');
  const INPUT={ArrowLeft:'left',ArrowRight:'right',KeyA:'left',KeyD:'right',Space:'fire',Enter:'fire',KeyP:'pause',Escape:'pause',KeyR:'retry'};
  window.addEventListener('keydown',e=>{const act=INPUT[e.code];if(!act)return;const tag=e.target instanceof HTMLElement?e.target.tagName:'';if(ui.menu.open){if(act==='pause'){e.preventDefault();if(menuMode==='pause'||menuMode==='about')closeMenu()}return}if((tag==='INPUT'&&['left','right','fire'].includes(act))||(['BUTTON','A'].includes(tag)&&act==='fire'))return;e.preventDefault();if(e.repeat)return;if(act==='pause')showMenu('pause');else if(act==='retry')startLevel(state.levelIndex);else if(act==='fire')fire();else if(state.phase==='ready'){keys.add(act);setAim(angle+(act==='left'?-.5:.5))}});
  window.addEventListener('keyup',e=>keys.delete(INPUT[e.code]));window.addEventListener('blur',()=>{keys.clear();if(ready&&!ui.menu.open&&state.phase!=='won'&&state.phase!=='lost')showMenu('pause')});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready&&!ui.menu.open&&state.phase!=='won'&&state.phase!=='lost')showMenu('pause')});
  ui.menu.addEventListener('cancel',e=>{e.preventDefault();if(menuMode==='pause'||menuMode==='about')closeMenu()});
  function frame(now){const dt=Math.min((now-lastTime)/1000||0,1/15);lastTime=now;if(ready){if(!paused){practiceSeconds+=dt;if(state.phase==='ready'){if(keys.has('left'))setAim(angle-dt*36);if(keys.has('right'))setAim(angle+dt*36)}accum+=dt;while(accum>=1/240){PegSim.step(state,1/240);accum-=1/240;}processEvents();if(toastTime>0){toastTime-=dt;if(toastTime<=0)ui.toast.classList.remove('on')}if(roundDelay>0){roundDelay-=dt;if(roundDelay<=0)showMenu(state.phase==='won'?'win':'lose')}}renderer.draw(state,angle,dt,paused);refresh()}requestAnimationFrame(frame)}
  function boot(){if(ready)return;renderer=new PegRenderer(ui.board,ui.mascot,image);ready=true;$('loading').hidden=true;startLevel(saved.unlocked);lastTime=performance.now();requestAnimationFrame(frame)}
  image.onload=boot;image.onerror=()=>{$('loading').textContent='奶蛙图片未能载入，请确认 assets 文件夹完整后刷新。';ui.fire.disabled=true;};if(image.complete&&image.naturalWidth)boot();
  // Read-only QA snapshot, never a state setter or automatic player.
  window.PegGame=Object.freeze({snapshot:()=>JSON.parse(JSON.stringify({phase:state.phase,levelIndex:state.levelIndex,ballsLeft:state.ballsLeft,remaining:PegSim.remaining(state),shots:state.shots,hits:state.hits,catches:state.catches,time:state.time,ball:state.ball,angle,paused,ready,menu:menuMode,unlocked:saved.unlocked,completed:saved.completed,practiceSeconds,playedShots})),version:'1.0.0'});
})();
