/* UI, rendering and input only. Gameplay rules live in core.js. No network or audio. */
(() => {
'use strict';
const C = TerritoryCore, $ = id => document.getElementById(id);
const canvas = $('board'), ctx = canvas.getContext('2d');
const atlas = new Image(); atlas.src = 'assets/naiwa-atlas.png';
const SAVE_KEY = 'naiwa-territory-v1';
const names = ['格纹餐布', '纸板小码头', '折页分岔口'];
let saved = {unlocked:0,best:[],completed:0};
try { const d=JSON.parse(localStorage.getItem(SAVE_KEY)); if(d && typeof d==='object'){saved.unlocked=Math.max(0,Math.min(2,Number(d.unlocked)||0));saved.best=Array.isArray(d.best)?d.best.slice(0,3):[];saved.completed=Math.max(0,Number(d.completed)||0);} } catch(e) {}
let state=C.createState(0), active=false, paused=false, modalMode='start', primaryAction=null, secondaryAction=null;
let runSeconds=0, runMistakes=0, recorded=false, held=[], pointerDir=null, pointerInputs=new Map(), swipeDir=null, swipePointer=null, acc=0, last=0, uiLast=0, fx=0, lastClosures=0, lastLives=3;
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
const keyDirs={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(saved));}catch(e){}}
function clearInput(){held=[];pointerDir=null;pointerInputs.clear();swipeDir=null;swipePointer=null;document.querySelectorAll('[data-dir]').forEach(b=>b.classList.remove('held'));}
function showModal(mode,title,copy,action,label,secondary,label2){modalMode=mode;clearInput();$('overlay').hidden=false;$('modal-title').textContent=title;$('modal-copy').innerHTML=copy;$('modal-kicker').textContent=mode==='won'?'这一桌，笑着拿下。':mode==='complete'?'三张桌面 · 全部拿下':'NAIWA · 圈地便签';$('modal-art').className='sticker '+(['won','complete'].includes(mode)?'sticker-laugh':'sticker-idle');document.querySelector('.modal').classList.toggle('compact',['help','credits','pause','confirm'].includes(mode));$('primary').innerHTML=label+' <span>→</span>';$('secondary').hidden=!secondary;$('secondary').textContent=label2||'';primaryAction=action;secondaryAction=secondary;$('primary').focus({preventScroll:true});}
function hideModal(){modalMode='';$('overlay').hidden=true;canvas.focus({preventScroll:true});clearInput();acc=0;last=performance.now();}
function begin(level, fresh=false){if(fresh){runSeconds=0;runMistakes=0;}state=C.createState(level);active=true;paused=false;recorded=false;fx=0;lastClosures=0;lastLives=3;$('pause').textContent='Ⅱ 暂停';hideModal();updateUI();}
function intro(){active=false;paused=false;showModal('start','胆子大，地盘大。','<p>沿绿色安全边缘出发，<b>画线接回</b>，地盘就归你。<br>别让巡游者碰到未闭合的橙线。</p><p>三桌目标 <b>60% → 65% → 70%</b> · 每桌 3 次机会</p>',()=>begin(0,true),'开始圈地',saved.unlocked>0?()=>begin(saved.unlocked,true):null,'继续第 '+(saved.unlocked+1)+' 桌');}
function pauseGame(){if(!active||paused||state.status!=='playing')return;paused=true;showModal('pause','歇一口气。','<p>时间、巡游者和正在画的线都已暂停。</p>',resume,'继续圈地',()=>begin(state.levelIndex??state.level??0),'重来这一桌');$('pause').textContent='▶ 继续';}
function resume(){paused=false;hideModal();$('pause').textContent='Ⅱ 暂停';}
function info(type){const wasPlaying=active&&state.status==='playing';const wasPaused=paused;paused=wasPlaying;const back=()=>{if(wasPlaying){paused=wasPaused;if(wasPaused){paused=false;pauseGame();}else resume();}else if(active&&state.status!=='playing')finish();else intro();};if(type==='help')showModal('help','圈一小块，还是赌一大圈？','<p><b>① 移动</b>　方向键 / WASD，或按住方向板。<br>触屏也可在场内向四向滑动并按住，松手就停。</p><p><b>② 接回</b>　离开绿色画线，接回绿色才填色。<br>有巡游者的地块会留下。反向走可以收回线路。</p><p><b>③ 大笑</b>　碰到绿色笑气后，空格或按钮推开附近巡游者。冷却 8 秒，最多存 2 次。</p><p>线被撞扣 1 次机会；每桌 3 次。<br>首桌最多保护 10 秒，首圈接回就会醒来。<br>后两桌准备 3 秒；P / Esc 暂停。</p>',back,'明白了');else showModal('credits','一张桌布，一只奶蛙。','<p>奶蛙角色参考由用户提供；本作是非官方同人。<br>角色贴图和边角装饰由内置 imagegen 生成。</p><p>网页代码、网格场地、巡游者及交互为本项目制作。<br>无外部依赖、无网络请求、无声音、无广告。<br>角色及生成素材不因代码授权而获得原 IP 权利。</p><p>制作与验证详见交付包中的来源和状态文件。</p>',back,'返回桌面');}
function finish(){clearInput();updateUI();const level=state.levelIndex??state.level??0;const mistakes=3-state.lives;if(state.status==='won'){if(!recorded){recorded=true;runSeconds+=state.elapsed;runMistakes+=mistakes;saved.unlocked=Math.max(saved.unlocked,Math.min(2,level+1));const prior=saved.best[level];if(!prior||state.elapsed<prior.time)saved.best[level]={time:Math.round(state.elapsed*10)/10,mistakes};if(level===2)saved.completed++;save();}if(level<2)showModal('won','这块地，我笑了！','<p>第 '+(level+1)+' 桌完成，准备换一张新桌布。</p><div class="stat-row"><span><b>'+Math.floor(state.claimed*100)+'%</b>圈下的地盘</span><span><b>'+Math.ceil(state.elapsed)+' 秒</b>本桌用时</span><span><b>'+state.lives+'</b>剩余机会</span></div>',()=>begin(level+1),'下一桌 · '+names[level+1],()=>begin(level),'再圈一次');else showModal('complete','三张桌子，都归你。','<p>奶蛙今天的地盘，有点大。</p><div class="stat-row"><span><b>'+Math.ceil(runSeconds)+' 秒</b>本次累计用时</span><span><b>'+runMistakes+'</b>累计失误</span><span><b>3 / 3</b>全部拿下</span></div><p>每桌最佳用时已保存在这台设备。</p>',()=>begin(0,true),'再圈三桌');}else showModal('lost',state.lives<=0?'线断了，气势还在。':'这桌时间到了。','<p>已经圈下 <b>'+Math.floor(state.claimed*100)+'%</b>。<br>先拿小块，把绿色边缘往前推；<br>收集笑气，再放心画大圈。</p>',()=>begin(level),'马上再来',intro,'回到开始');}
$('primary').addEventListener('click',()=>primaryAction?.());$('secondary').addEventListener('click',()=>secondaryAction?.());
$('pause').addEventListener('click',()=>paused&&modalMode==='pause'?resume():pauseGame());$('help').addEventListener('click',()=>info('help'));$('credits').addEventListener('click',()=>info('credits'));
$('retry').addEventListener('click',()=>{if(!active){begin(0,true);return;}if(state.status!=='playing'){begin(state.levelIndex);return;}paused=true;showModal('confirm','重画这一桌？','<p>本桌的圈地会重新开始，已经解锁的桌面会保留。</p>',()=>begin(state.levelIndex??state.level??0),'重新开始',resume,'继续当前这一桌');});
function useLaugh(){if(active&&!paused&&!modalMode&&state.status==='playing'){if(C.laugh(state))fx=1;updateUI();}}
$('laugh').addEventListener('click',useLaugh);
document.addEventListener('keydown',e=>{if(keyDirs[e.code]){if(active&&!paused&&!modalMode){e.preventDefault();if(!e.repeat&&!held.includes(e.code))held.push(e.code);}}else if(e.code==='Space'){if(active&&!paused&&!modalMode){e.preventDefault();if(!e.repeat)useLaugh();}}else if(e.code==='KeyP'||e.code==='Escape'){e.preventDefault();if(paused&&modalMode==='pause')resume();else if(!modalMode)pauseGame();}});
document.addEventListener('keyup',e=>{if(keyDirs[e.code])held=held.filter(k=>k!==e.code);});
document.querySelectorAll('[data-dir]').forEach(button=>{button.addEventListener('pointerdown',e=>{e.preventDefault();if(!active||paused||modalMode)return;pointerInputs.set(e.pointerId,button.dataset.dir);pointerDir=button.dataset.dir;button.setPointerCapture(e.pointerId);button.classList.add('held');});const release=e=>{pointerInputs.delete(e.pointerId);pointerDir=[...pointerInputs.values()].at(-1)||null;button.classList.remove('held');};button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',release);});
canvas.addEventListener('pointerdown',e=>{if(!active||paused||modalMode||swipePointer)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);swipePointer={id:e.pointerId,x:e.clientX,y:e.clientY};});
canvas.addEventListener('pointermove',e=>{if(!swipePointer||e.pointerId!==swipePointer.id)return;const dx=e.clientX-swipePointer.x,dy=e.clientY-swipePointer.y;if(Math.hypot(dx,dy)<12)return;swipeDir=Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up';swipePointer.x=e.clientX;swipePointer.y=e.clientY;});
['pointerup','pointercancel','lostpointercapture'].forEach(ev=>canvas.addEventListener(ev,e=>{if(!swipePointer||e.pointerId!==swipePointer.id)return;swipeDir=null;swipePointer=null;}));
window.addEventListener('blur',()=>{clearInput();if(active&&!paused&&!modalMode)pauseGame();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(active&&!paused&&!modalMode)pauseGame();}});
function updateUI(){const level=state.levelIndex??state.level??0;$('level-name').textContent=String(level+1).padStart(2,'0')+' / '+names[level];$('percent').textContent=Math.floor(state.claimed*100);$('target').textContent=Math.round(state.target*100);$('progress').style.width=(state.claimed*100)+'%';$('target-marker').style.left=(state.target*100)+'%';$('lives').textContent=Array.from({length:3},(_,i)=>i<state.lives?'●':'○').join(' ');$('lives').setAttribute('aria-label','剩余'+state.lives+'次机会');const seconds=Math.max(0,Math.ceil(state.timeLimit-state.elapsed));$('timer').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');$('timer').style.color=seconds<20?'#ba512d':'';$('laugh').classList.toggle('ready',state.energy>0&&state.cooldown<=0);$('laugh-status').textContent=state.cooldown>0?'冷却 '+Math.ceil(state.cooldown)+' 秒 · 存 '+state.energy+' 次':state.energy>0?'笑气 × '+state.energy+' · 现在能用':'先碰到绿色笑气';$('laugh').setAttribute('aria-disabled',String(!(state.energy>0&&state.cooldown<=0)));document.querySelectorAll('.level-dots i').forEach((el,i)=>{el.className=i===level?'active':i<level?'done':'';});const best=saved.best[level];$('record').textContent=best?'本桌最佳 '+best.time+' 秒':'三张桌面，圈下就归你。';let text='小块稳拿，大圈冒险。巡游者前方虚线表示移动方向。';if(state.feedback?.ttl>0)text=state.feedback.text;else if(state.grace>0)text=state.levelIndex===0?'教学保护 '+Math.ceil(state.grace)+' 秒：沿虚线走出去，再接回绿色边缘。':'准备保护 '+Math.ceil(state.grace)+' 秒：从绿色平台出发，把新线路接回。';else if(state.trail.length)text='橙线还不安全！接回任意绿色地块，才会完成占领。';else if(state.energy===0)text='绿色气泡是笑气：走过去收集，危险时用大笑推开巡游者。';$('notice').textContent=text;}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function sprite(kind,x,y,h){if(!atlas.complete||!atlas.naturalWidth)return;const src=kind==='laugh'?[574,26,720,851]:[65,23,487,850];const w=src[2]/src[3]*h;ctx.drawImage(atlas,...src,x-w/2,y-h,w,h);}
function draw(now){const s=state,t=now/1000,cell=20;ctx.clearRect(0,0,800,640);ctx.fillStyle=['#f4ecd5','#ebdbc0','#f3e5cc'][s.levelIndex??s.level??0];ctx.fillRect(0,0,800,640);for(let y=0;y<C.H;y++)for(let x=0;x<C.W;x++){const safe=s.grid[y*C.W+x]===1;if(safe){ctx.fillStyle=(x+y)%2?'#b9ce9e':'#b4c999';ctx.fillRect(x*cell,y*cell,cell,cell);}else{if((Math.floor(x/4)+Math.floor(y/4))%2===0){ctx.fillStyle='#d7c9a01d';ctx.fillRect(x*cell,y*cell,cell,cell);}ctx.fillStyle='#ab997c42';ctx.fillRect(x*cell+9,y*cell+9,1.5,1.5);}}
// Crisp perimeter on claimed land; grid is gameplay, never a raster UI.
ctx.strokeStyle='#81986b';ctx.lineWidth=1.5;ctx.beginPath();for(let y=1;y<C.H-1;y++)for(let x=1;x<C.W-1;x++)if(s.grid[y*C.W+x]===1){if(s.grid[y*C.W+x+1]===0){ctx.moveTo((x+1)*20,y*20);ctx.lineTo((x+1)*20,(y+1)*20);}if(s.grid[(y+1)*C.W+x]===0){ctx.moveTo(x*20,(y+1)*20);ctx.lineTo((x+1)*20,(y+1)*20);}if(s.grid[y*C.W+x-1]===0){ctx.moveTo(x*20,y*20);ctx.lineTo(x*20,(y+1)*20);}if(s.grid[(y-1)*C.W+x]===0){ctx.moveTo(x*20,y*20);ctx.lineTo((x+1)*20,y*20);}}ctx.stroke();
if(s.levelIndex===0&&s.grace>0&&s.closures===0){ctx.save();ctx.setLineDash([9,7]);ctx.strokeStyle='#e28a40';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(130,30);ctx.lineTo(130,170);ctx.lineTo(290,170);ctx.lineTo(290,30);ctx.stroke();ctx.restore();ctx.fillStyle='#927b52';ctx.font='bold 15px "Microsoft YaHei",sans-serif';ctx.fillText('沿虚线，圈一小块',135,206);}
for(const g of s.gas){if(g.collected)continue;const x=(g.x+.5)*cell,y=(g.y+.5)*cell,r=8+Math.sin(t*3+g.x)*1;ctx.fillStyle='#64a77724';ctx.beginPath();ctx.arc(x,y,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e8f3bc';ctx.strokeStyle='#558453';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#4b794c';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText('+',x,y+4);ctx.textAlign='left';}
if(s.trail.length){ctx.save();ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();ctx.moveTo((s.anchor.x+.5)*20,(s.anchor.y+.5)*20);for(const p of s.trail)ctx.lineTo((p.x+.5)*20,(p.y+.5)*20);ctx.lineWidth=12;ctx.strokeStyle='#fff8d5';ctx.stroke();ctx.lineWidth=6;ctx.strokeStyle='#e87d32';ctx.stroke();ctx.restore();}
for(const e of s.enemies){const x=e.x*20,y=e.y*20,v=Math.hypot(e.vx,e.vy)||1;ctx.save();ctx.strokeStyle=s.grace>0?'#8d937466':'#855d4b66';ctx.setLineDash([4,5]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+e.vx/v*44,y+e.vy/v*44);ctx.stroke();ctx.setLineDash([]);ctx.translate(x,y);ctx.rotate(t*(e.vx>0?.3:-.3));ctx.beginPath();for(let i=0;i<16;i++){const a=i*Math.PI/8,r=i%2?10:13;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fillStyle=e.stun>0?'#aab59c':'#866359';ctx.fill();ctx.strokeStyle='#634f45';ctx.lineWidth=2;ctx.stroke();ctx.restore();ctx.fillStyle='#fff6dd';ctx.beginPath();ctx.arc(x-3,y-2,2.6,0,Math.PI*2);ctx.arc(x+4,y-2,2.6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#443f32';ctx.fillRect(x-2,y-2,1.8,2);ctx.fillRect(x+4,y-2,1.8,2);if(s.grace>0){ctx.fillStyle='#67775b';ctx.font='bold 12px sans-serif';ctx.fillText('z',x+13,y-15);}}
const px=(s.player.x+.5)*20,py=(s.player.y+.5)*20;ctx.save();if(s.invulnerable>0)ctx.globalAlpha=.65+Math.sin(t*15)*.3;ctx.fillStyle='#50604130';ctx.beginPath();ctx.ellipse(px,py+6,15,6,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=s.trail.length?'#df6f25':'#426948';ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(px,py,8,0,Math.PI*2);ctx.stroke();sprite(fx>.1?'laugh':'idle',Math.max(22,Math.min(778,px)),Math.max(56,Math.min(639,py+11)),55);ctx.restore();if(fx>0){ctx.strokeStyle='#e6b842';ctx.globalAlpha=fx*.65;ctx.lineWidth=7*fx;ctx.beginPath();ctx.arc(px,py,(1-fx)*190+15,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}if(s.lastClaim>0&&s.feedback?.type==='claim'&&s.feedback.ttl>0){ctx.fillStyle='#385641';ctx.font='900 26px "Microsoft YaHei",sans-serif';ctx.textAlign='center';ctx.fillText('圈下了！',400,48);ctx.textAlign='left';}}
function tick(now){if(!last)last=now;const frame=Math.min((now-last)/1000,.1);last=now;if(active&&!paused&&!modalMode&&state.status==='playing'){acc+=frame;let n=0;while(acc>=1/60&&n++<6){const d=dirs[pointerDir||swipeDir||keyDirs[held[held.length-1]]]||[0,0];C.step(state,1/60,{dx:d[0],dy:d[1]});fx=Math.max(0,fx-1/60);acc-=1/60;if(state.status!=='playing'){finish();break;}}}else acc=0;if(now-uiLast>80){updateUI();uiLast=now;}draw(now);requestAnimationFrame(tick);}
intro();updateUI();requestAnimationFrame(tick);
})();
