(function(){
  'use strict';
  const $=id=>document.getElementById(id),sim=window.TraySim,renderer=window.TrayRender;
  const KEY='naiwa-tray-v1',DT=1/120;let state=sim.create(0),mode='menu',previous=0,accumulator=0,lastEvent=0,feedbackUntil=0;
  const input={x:450},keys=new Set();let save={version:1,unlocked:0,completed:[],best:[]};
  try {const value=JSON.parse(localStorage.getItem(KEY));if(value?.version===1){save.unlocked=Math.max(0,Math.min(5,Number(value.unlocked)||0));save.completed=Array.isArray(value.completed)?value.completed.filter(v=>Number.isInteger(v)&&v>=0&&v<6):[];save.best=Array.isArray(value.best)?value.best:[];}}catch{}
  const writeSave=()=>{try{localStorage.setItem(KEY,JSON.stringify(save));}catch{}};
  function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function setScreen(html){$('menu-card').innerHTML=html;$('screen').classList.remove('hidden');$('pause').disabled=true;$('laugh').disabled=true;$('balance').disabled=true;$('center').disabled=true;keys.clear();accumulator=0;const button=$('menu-card').querySelector('.primary');button?.focus({preventScroll:true});}
  function start(stage){state=sim.create(stage);input.x=450;$('balance').value='450';lastEvent=0;feedbackUntil=0;mode='playing';accumulator=0;previous=performance.now();$('screen').classList.add('hidden');$('pause').disabled=false;$('balance').disabled=false;$('center').disabled=false;$('feedback').className='feedback';$('feedback').textContent=state.stage.tip||'正品稳住，错单按箭头送去回收口。';$('board').focus({preventScroll:true});updateUI();}
  function welcome(){mode='menu';state=sim.create(0);setScreen(`<span class="kicker">STEADY HANDS. BIG LAUGHS.</span><h3>端稳，或者笑一下。</h3><div class="menu-steps"><span><b>① 稳住正品</b>盘上稳住 7 秒</span><span><b>② 看箭头选边</b>错单送进回收口</span><span><b>③ 笑着抛出去</b>离支点越远，弹得越远</span></div><button class="primary" id="start">${save.unlocked>0?'继续第 '+(save.unlocked+1)+' 单':'开餐 · 开始第一单'}</button><p>拖动支点 + 点「笑一下」 · 6 单约 3 分钟</p>${save.unlocked>0?'<button class="secondary" id="choose">选择订单</button>':''}`);$('start').onclick=()=>start(save.unlocked);if($('choose'))$('choose').onclick=menu;updateUI();}
  function menu(){if(mode==='playing')mode='paused';setScreen(`<span class="kicker">TODAY'S SIX ORDERS</span><h3>今天，端哪桌？</h3><div class="stage-grid">${sim.STAGES.map((s,i)=>`<button data-stage="${i}" ${i>save.unlocked?'disabled':''}><b>${i>save.unlocked?'锁':String(i+1).padStart(2,'0')}</b>${escapeHTML(s.title)}${save.completed.includes(i)?' ✓':''}</button>`).join('')}</div>${state.status==='playing'&&state.time>0?'<button class="primary" id="resume">继续当前订单</button>':'<button class="primary" id="start">开始第一单</button>'}`);$('menu-card').querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>start(Number(b.dataset.stage)));if($('resume'))$('resume').onclick=resume;if($('start'))$('start').onclick=()=>start(0);}
  function pause(){if(mode!=='playing')return;mode='paused';setScreen('<span class="kicker">TAKE A BREATH</span><h3>盘子帮你定住了。</h3><p>暂停期间不会计时，也不会积攒笑意。</p><button class="primary" id="resume">继续端盘</button><button class="secondary" id="retry">重来本单</button>');$('resume').onclick=resume;$('retry').onclick=()=>start(state.stageIndex);}
  function resume(){mode='playing';accumulator=0;previous=performance.now();$('screen').classList.add('hidden');$('pause').disabled=false;$('balance').disabled=false;$('center').disabled=false;}
  function finish(){mode='result';const won=state.status==='won',last=state.stageIndex===5;
    if(won){save.unlocked=Math.max(save.unlocked,Math.min(5,state.stageIndex+1));if(!save.completed.includes(state.stageIndex))save.completed.push(state.stageIndex);save.best[state.stageIndex]=Math.max(save.best[state.stageIndex]||0,state.score);writeSave();}
    const cause=state.reason||state.message||state.events.slice().reverse().find(e=>e.type==='lost')?.text||(state.mistakes>=3?'这次掉落或分错了三件。':'收餐了，盘上还有没有处理完的订单。');
    setScreen(`<span class="kicker">${won?'ORDER COMPLETE':'ONE MORE TRY'}</span><h3>${won?(last?'这桌，端住了！':'第 '+(state.stageIndex+1)+' 单，收工。'):'没关系，再端一次。'}</h3><p>${won?(last?'六段订单完成。奶蛙今天也没白笑。':'下一桌有新的物性和错单组合。'):escapeHTML(cause)}</p><div class="result-stats"><span><b>${state.served}/${state.totalGood}</b>正品上桌</span><span><b>${state.sorted}/${state.totalBad}</b>错单回收</span><span><b>${state.mistakes}</b>失误</span></div><button class="primary" id="next">${won?(last?'再端一轮':'下一单 · '+escapeHTML(sim.STAGES[state.stageIndex+1]?.title||'')):'马上重来本单'}</button><button class="secondary" id="choose">选择订单</button>`);
    $('next').onclick=()=>start(won?(last?0:state.stageIndex+1):state.stageIndex);$('choose').onclick=menu;
  }
  function laugh(){if(mode==='playing'&&state.cooldown<=0){sim.laugh(state);updateUI();}}
  function updateUI(){const playing=mode==='playing';$('order-number').textContent='订单 '+String(state.stageIndex+1).padStart(2,'0')+' / 06';$('order-title').textContent=state.stage.title;$('served').textContent=state.served+' / '+state.totalGood;$('sorted').textContent=state.sorted+' / '+state.totalBad;$('mistakes').textContent=state.mistakes+' / 3';$('mistake-label').style.color=state.mistakes>=2?'#b84e3c':'';$('time').textContent=String(Math.max(0,Math.ceil(state.stage.duration-state.time))).padStart(2,'0');$('laugh').disabled=!playing||state.cooldown>0;$('laugh-title').textContent=state.cooldown>0?'缓一口…':'笑一下！';$('meter-fill').style.width=(state.laughMeter*100)+'%';const warning=state.laughMeter>=7/9;$('laugh-status').parentElement.classList.toggle('warning',warning);$('laugh-warning').textContent=warning?'即将连笑 × 3':'笑一下可清空';$('scene-caption').textContent=state.time<8?'正品稳住 7 秒 · 错单笑着送走':state.stage.tip;
    const e=state.events.filter(e=>e.id>lastEvent).slice(-1)[0];if(e){lastEvent=e.id;feedbackUntil=state.time+2.6;$('feedback').textContent=e.text||'';$('feedback').className='feedback'+(e.type==='mistake'?' bad':'');}
    if(state.time>feedbackUntil&&mode==='playing'){$('feedback').textContent=state.stage.tip;$('feedback').className='feedback';}
    // Public DOM state supports non-invasive QA without changing game state.
    $('board').dataset.status=mode==='playing'?state.status:mode;$('board').dataset.stage=String(state.stageIndex+1);$('board').dataset.time=state.time.toFixed(2);$('board').dataset.served=String(state.served);$('board').dataset.sorted=String(state.sorted);$('board').dataset.pivot=state.pivot.toFixed(1);
  }
  $('balance').oninput=e=>{input.x=Number(e.target.value);};$('center').onclick=()=>{input.x=450;$('balance').value='450';};$('laugh').onclick=laugh;$('pause').onclick=pause;$('menu-button').onclick=menu;
  let dragging=false;
  const point=e=>{const b=$('board').getBoundingClientRect();input.x=Math.max(310,Math.min(590,(e.clientX-b.left)*900/b.width));$('balance').value=String(input.x);};
  $('board').onpointerdown=e=>{if(mode!=='playing')return;dragging=true;$('board').setPointerCapture(e.pointerId);point(e);};$('board').onpointermove=e=>{if(dragging&&mode==='playing')point(e);};$('board').onpointerup=$('board').onpointercancel=()=>{dragging=false;};
  document.addEventListener('keydown',e=>{const code=e.code;if(['ArrowLeft','ArrowRight','ArrowDown','Space'].includes(code)&&mode==='playing'){e.preventDefault();}if(e.repeat)return;if(code==='KeyP'||code==='Escape'){if(mode==='playing')pause();else if(mode==='paused')resume();return;}if(mode!=='playing')return;if(code==='Space')laugh();if(code==='KeyR')start(state.stageIndex);if(code==='ArrowDown'){input.x=450;$('balance').value='450';}if(code==='ArrowLeft'||code==='KeyA')input.x=Math.max(310,input.x-12);if(code==='ArrowRight'||code==='KeyD')input.x=Math.min(590,input.x+12);keys.add(code);});document.addEventListener('keyup',e=>keys.delete(e.code));
  window.addEventListener('blur',()=>{keys.clear();dragging=false;pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
  function frame(now){const elapsed=Math.min(.1,Math.max(0,(now-previous)/1000));previous=now;
    if(mode==='playing'){accumulator+=elapsed;while(accumulator>=DT){if(keys.has('ArrowLeft')||keys.has('KeyA'))input.x=Math.max(310,input.x-190*DT);if(keys.has('ArrowRight')||keys.has('KeyD'))input.x=Math.min(590,input.x+190*DT);sim.step(state,DT,input);accumulator-=DT;if(state.status!=='playing'){finish();break;}}$('balance').value=String(input.x);}
    updateUI();renderer.render($('board'),state,{preview:mode==='menu'});requestAnimationFrame(frame);
  }
  renderer.loadAssets().then(results=>{if(results.some(v=>!v)){$('feedback').textContent='角色图片未加载，请检查 assets 文件夹是否完整。';}welcome();previous=performance.now();requestAnimationFrame(frame);});
})();
